# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  vmImage: ubuntu-latest

jobs:
  
  - job: checkout
    steps:
      - checkout: self
  - deployment: deploy_app
    displayName: 'Deploy application'
    dependsOn: checkout
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - task: FusionApp@2
            displayName: 'Deploying app'
            inputs:
              action: deploy
              appKey: "dcd"
              bundlePath: "$(Build.SourcesDirectory)/frontend/out/dcd.zip"
              fusionCredentials: 'conceptapp-preprod'
              tokenResource: "f8fbc211-ab05-404b-b94e-e3abdc364f22"
              portalUrl: "https://pro-s-portal-ci.azurewebsites.net"
              forceReplaceExisting: "True"
              ignoreVersionConflict: "True"